# Generated by Django 6.0.1 on 2026-01-28 20:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, max_length=15, null=True)),
                ('colours', models.CharField(blank=True, max_length=48, null=True)),
                ('measures', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keycaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, max_length=15, null=True)),
                ('layaut', models.CharField(blank=True, max_length=6, null=True)),
                ('colours', models.CharField(blank=True, max_length=48, null=True)),
                ('profile', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('colour', models.CharField(blank=True, max_length=16, null=True)),
                ('emblem', models.ImageField(blank=True, null=True, upload_to='emblem/')),
            ],
        ),
        migrations.CreateModel(
            name='Pcb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectivity', models.CharField(blank=True, max_length=50, null=True)),
                ('measures', models.CharField(blank=True, max_length=30, null=True)),
                ('layaut', models.CharField(blank=True, max_length=10, null=True)),
                ('rgb', models.BooleanField(default=True)),
                ('hotswap', models.BooleanField(default=True)),
                ('firmware', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, max_length=15, null=True)),
                ('measures', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('website', models.URLField()),
                ('image', models.ImageField(upload_to='logos_socialnetworks')),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
                ('force', models.DecimalField(decimal_places=2, max_digits=5)),
                ('point', models.DecimalField(decimal_places=2, max_digits=5)),
                ('route', models.DecimalField(decimal_places=2, max_digits=5)),
                ('useful_life', models.IntegerField()),
                ('pin_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('image', models.ImageField(upload_to='image_users/')),
                ('bio', models.TextField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('brand', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('shopping_website', models.URLField()),
                ('case', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.case')),
                ('keycaps', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.keycaps')),
                ('pcb', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pcb')),
                ('plate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.plate')),
            ],
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('colours', models.CharField(max_length=48)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('stars', models.DecimalField(decimal_places=1, max_digits=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KeyboardComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modification', models.DateField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.component')),
                ('keyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.keyboard')),
            ],
        ),
        migrations.AddField(
            model_name='keyboard',
            name='component',
            field=models.ManyToManyField(related_name='components', through='core.KeyboardComponent', to='core.component'),
        ),
        migrations.CreateModel(
            name='GetLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_get', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.level')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.ManyToManyField(related_name='levels', through='core.GetLevel', to='core.level'),
        ),
        migrations.CreateModel(
            name='SocialNetworkUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('url', models.URLField()),
                ('social_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.socialnetwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='social_network',
            field=models.ManyToManyField(related_name='networks', through='core.SocialNetworkUser', to='core.socialnetwork'),
        ),
    ]
