# Generated by Django 6.0.1 on 2026-01-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
