# Generated by Django 6.0.1 on 2026-01-28 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_level_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='name',
        ),
    ]
