# Generated by Django 6.0.1 on 2026-01-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_component_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
