# Generated by Django 6.0.1 on 2026-01-31 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_socialnetwork_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getlevel',
            name='level',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.level'),
        ),
        migrations.AlterField(
            model_name='level',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
