# Generated by Django 6.0.1 on 2026-01-31 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_getlevel_level_alter_level_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getlevel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='level',
            name='number',
            field=models.IntegerField(),
        ),
    ]
