# Generated by Django 6.0.1 on 2026-01-31 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_getlevel_user_alter_level_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetworkuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to=settings.AUTH_USER_MODEL),
        ),
    ]
