# Generated by Django 6.0.1 on 2026-01-31 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_socialnetworkuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getlevel',
            name='level',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='core.level'),
        ),
    ]
