# Generated by Django 6.0.1 on 2026-01-31 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_getlevel_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetworkuser',
            name='social_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_networks_user', to='core.socialnetwork'),
        ),
    ]
