# Generated by Django 6.0.1 on 2026-02-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_socialnetworkuser_social_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dateofbirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
