# Generated by Django 6.0.1 on 2026-02-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_dateofbirth_alter_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, null=True),
        ),
    ]
