# Generated by Django 6.0.1 on 2026-02-02 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyboards', to=settings.AUTH_USER_MODEL),
        ),
    ]
