# Generated by Django 6.0.1 on 2026-02-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_keyboard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='logos_socialnetworks'),
        ),
        migrations.AlterField(
            model_name='socialnetworkuser',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialnetworkuser',
            name='username',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
