# Generated by Django 6.0.1 on 2026-02-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_socialnetwork_image_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='socialnetworkuser',
            constraint=models.UniqueConstraint(fields=('user', 'social_network'), name='social_user_unique'),
        ),
    ]
