# Generated by Django 6.0.1 on 2026-02-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_socialnetworkuser_social_user_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='case',
        ),
        migrations.RemoveField(
            model_name='component',
            name='keycaps',
        ),
        migrations.RemoveField(
            model_name='component',
            name='pcb',
        ),
        migrations.RemoveField(
            model_name='component',
            name='plate',
        ),
        migrations.AddField(
            model_name='component',
            name='type',
            field=models.CharField(choices=[('KC', 'Keycaps'), ('CS', 'Case'), ('PL', 'Plate'), ('PB', 'PCB'), ('SW', 'Switch')], max_length=2, null=True),
        ),
    ]
