# Generated by Django 6.0.1 on 2026-02-04 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_component_case_remove_component_keycaps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboardcomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='core.component'),
        ),
        migrations.AlterField(
            model_name='keyboardcomponent',
            name='date_modification',
            field=models.DateField(auto_now_add=True),
        ),
    ]
