# Generated by Django 6.0.1 on 2026-02-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_keyboardcomponent_component_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='type',
            field=models.CharField(blank=True, choices=[('KC', 'Keycaps'), ('CS', 'Case'), ('PL', 'Plate'), ('PB', 'PCB'), ('SW', 'Switch')], max_length=2, null=True),
        ),
    ]
