# Generated by Django 6.0.1 on 2026-02-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_component_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getlevel',
            name='datetime_get',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
