# Generated by Django 6.0.1 on 2026-02-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_getlevel_datetime_get'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='Keycaps',
        ),
        migrations.DeleteModel(
            name='Pcb',
        ),
        migrations.DeleteModel(
            name='Plate',
        ),
        migrations.DeleteModel(
            name='Switch',
        ),
        migrations.AddField(
            model_name='keyboard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='keyboards/'),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='component',
            field=models.ManyToManyField(related_name='keyboards', through='core.KeyboardComponent', to='core.component'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
