# Generated by Django 6.0.1 on 2026-02-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_getlevel_datetime_get'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
