# Generated by Django 6.0.1 on 2026-02-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_delete_case_delete_keycaps_delete_pcb_delete_plate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='keyboards/'),
        ),
    ]
